In [1]:
import d2lzh as d2l
from mxnet import nd

In [4]:
# 多输入，单输出
def corr2d_multi_in(X, K):
    return nd.add_n(*[d2l.corr2d(x, k) for x, k in zip(X, K)])

In [7]:
# X = nd.array([[[0, 1, 2], 
#                [3, 4, 5],
#                [6, 7, 8]],
#               [[1, 2, 3],
#                [4, 5, 6],
#                [7, 8, 9]]])
# X = nd.array([[[0, 1, 2], 
#                [3, 4, 5],
#                [6, 7, 8]],
#               [[1, 2, 3],
#                [4, 5, 6],
#                [7, 8, 9]],
#               [[1, 2, 3],
#                [4, 5, 6],
#                [7, 8, 9]]])
K = nd.array([[[0, 1], 
               [2, 3]], 
              [[1, 2], 
               [3, 4]]])
corr2d_multi_in(X, K)



[[ 56.  72.]
 [104. 120.]]
<NDArray 2x2 @cpu(0)>

In [8]:
# 多输入，多输出
def corr2d_multi_in_out(X, K):
    return nd.stack(*[corr2d_multi_in(X, k) for k in K])

In [10]:
K = nd.stack(K, K + 1, K + 2)
K.shape

(3, 2, 2, 2)

In [11]:
corr2d_multi_in_out(X, K)


[[[ 56.  72.]
  [104. 120.]]

 [[ 76. 100.]
  [148. 172.]]

 [[ 96. 128.]
  [192. 224.]]]
<NDArray 3x2x2 @cpu(0)>

In [12]:
# 1*1的卷积层等价于全连接层，可以用矩阵乘法实现
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h * w))
    K = K.reshape((c_o, c_i))
    Y = nd.dot(K, X)
    return Y.reshape((c_o, h, w))

In [13]:
X = nd.random.uniform(shape=(3, 3, 3))
K = nd.random.uniform(shape=(2, 3, 1, 1))

Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)

In [14]:
Y1


[[[0.63251853 0.7027089  0.8923846 ]
  [1.0109798  0.70354044 0.9426006 ]
  [0.65125    0.909348   0.68587   ]]

 [[0.45974678 0.47996217 0.3274668 ]
  [0.3736128  0.2560653  0.66247874]
  [0.09572    0.7063811  0.23235497]]]
<NDArray 2x3x3 @cpu(0)>

In [15]:
Y2
# Y2与Y1不完全相等，属于数值问题


[[[0.63251853 0.70270896 0.8923846 ]
  [1.0109798  0.70354044 0.9426006 ]
  [0.65125    0.909348   0.68587   ]]

 [[0.45974678 0.47996217 0.3274668 ]
  [0.37361276 0.2560653  0.66247874]
  [0.09572    0.7063811  0.23235497]]]
<NDArray 2x3x3 @cpu(0)>